### ISSUE TITLE
Cannot create a CFT referencing a User

### ISSUE THREAD

**Issue by smichea** [meveo-org/meveo#10]
in https://case.wdintegration.site/ i created a CJCHCase entity as a table then added a CASE_NAME CFT of type String, then added a CFT "REVIEWER" that is an entity reference to User -> the cft was not created and it is not possible to edit the CET anymore (the logs are still available)

**Comment by smichea** [comment]
Caused by: java.lang.NullPointerException
	at org.meveo.admin.action.crm.CustomFieldTemplateBean.getCetId(CustomFieldTemplateBean.java:674)
	at org.meveo.admin.action.crm.CustomFieldTemplateBean$Proxy$_$$_WeldSubclass.getCetId(Unknown Source)
