### ISSUE TITLE
Allow CET audited field to be updated

### ISSUE THREAD

**Issue by czetsuya** [meveo-org/meveo#195]
When making a CET auditable it should create the table (or update them) using liquibase.

Then if not audited the table is dropped.

**Comment by smichea** [comment]
download social_lookup from central, disable all notif, fix non compiling scripts.
Create a social account CEI.
edit the social account CET, set it auditable
then ecit the TEL CFT of that CET and set it auditable
edit the social account CEI, the page is blank.

```
2020-10-13 02:04:55,080 INFO  [liquibase.executor.jvm.JdbcExecutor] (default task-16) SELECT COUNT(*) FROM public.databasechangeloglock
2020-10-13 02:04:55,080 INFO  [liquibase.executor.jvm.JdbcExecutor] (default task-16) SELECT COUNT(*) FROM public.databasechangeloglock
2020-10-13 02:04:55,080 INFO  [liquibase.executor.jvm.JdbcExecutor] (default task-16) SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1
2020-10-13 02:04:55,084 INFO  [liquibase.lockservice.StandardLockService] (default task-16) Successfully acquired change log lock
2020-10-13 02:04:55,107 INFO  [liquibase.executor.jvm.JdbcExecutor] (default task-16) SELECT MD5SUM FROM public.databasechangelog WHERE MD5SUM IS NOT NULL LIMIT 1
2020-10-13 02:04:55,107 INFO  [liquibase.executor.jvm.JdbcExecutor] (default task-16) SELECT COUNT(*) FROM public.databasechangelog
2020-10-13 02:04:55,108 INFO  [liquibase.changelog.StandardChangeLogHistoryService] (default task-16) Reading from public.databasechangelog
2020-10-13 02:04:55,108 INFO  [liquibase.executor.jvm.JdbcExecutor] (default task-16) SELECT * FROM public.databasechangelog ORDER BY DATEEXECUTED ASC, ORDEREXECUTED ASC
2020-10-13 02:04:55,118 INFO  [liquibase.executor.jvm.JdbcExecutor] (default task-16) ALTER TABLE public.social_account ALTER COLUMN  tel DROP NOT NULL
2020-10-13 02:04:55,118 INFO  [liquibase.changelog.ChangeSet] (default task-16) Null constraint dropped from social_account.tel
2020-10-13 02:04:55,119 INFO  [liquibase.changelog.ChangeSet] (default task-16) ChangeSet meveo::social_account_CT_tel_RNN_1602547495072::Meveo ran successfully in 2ms
2020-10-13 02:04:55,119 INFO  [liquibase.executor.jvm.JdbcExecutor] (default task-16) SELECT MAX(ORDEREXECUTED) FROM public.databasechangelog
2020-10-13 02:04:55,120 INFO  [liquibase.executor.jvm.JdbcExecutor] (default task-16) INSERT INTO public.databasechangelog (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('social_account_CT_tel_RNN_1602547495072', 'Meveo', 'meveo', NOW(), 444, '8:bf8334f1655f4afec996714aa8131a04', 'dropNotNullConstraint columnName=tel, tableName=social_account', '', 'EXECUTED', NULL, NULL, '3.8.5', '2547495113')
2020-10-13 02:04:55,124 INFO  [liquibase.executor.jvm.JdbcExecutor] (default task-16) ALTER TABLE public.social_account ALTER COLUMN  tel SET DEFAULT NULL
2020-10-13 02:04:55,124 INFO  [liquibase.changelog.ChangeSet] (default task-16) Default value dropped from social_account.tel
2020-10-13 02:04:55,126 INFO  [liquibase.changelog.ChangeSet] (default task-16) ChangeSet meveo::social_account_CT_tel_RD_1602547495073::Meveo ran successfully in 3ms
2020-10-13 02:04:55,126 INFO  [liquibase.executor.jvm.JdbcExecutor] (default task-16) INSERT INTO public.databasechangelog (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('social_account_CT_tel_RD_1602547495073', 'Meveo', 'meveo', NOW(), 445, '8:d26f3331b95355062581de29e850e73b', 'dropDefaultValue columnName=tel, tableName=social_account', '', 'EXECUTED', NULL, NULL, '3.8.5', '2547495113')
2020-10-13 02:04:55,130 INFO  [liquibase.executor.jvm.JdbcExecutor] (default task-16) ALTER TABLE public.social_account ALTER COLUMN tel TYPE VARCHAR(20) USING (tel::VARCHAR(20))
2020-10-13 02:04:55,133 INFO  [liquibase.changelog.ChangeSet] (default task-16) social_account.tel datatype was changed to varchar(20)
2020-10-13 02:04:55,134 INFO  [liquibase.executor.jvm.JdbcExecutor] (default task-16) ALTER TABLE social_account DROP CONSTRAINT IF EXISTS uk_social_account_tel
2020-10-13 02:04:55,137 INFO  [liquibase.changelog.ChangeSet] (default task-16) Custom SQL executed
2020-10-13 02:04:55,138 INFO  [liquibase.changelog.ChangeSet] (default task-16) ChangeSet meveo::social_account_CT_tel_M_1602547495073::Meveo ran successfully in 9ms
2020-10-13 02:04:55,139 INFO  [liquibase.executor.jvm.JdbcExecutor] (default task-16) INSERT INTO public.databasechangelog (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('social_account_CT_tel_M_1602547495073', 'Meveo', 'meveo', NOW(), 446, '8:90cb6329cc0d6f821cad178a3310dd9b', 'modifyDataType columnName=tel, tableName=social_account; sql', '', 'EXECUTED', NULL, NULL, '3.8.5', '2547495113')
2020-10-13 02:04:55,144 INFO  [liquibase.lockservice.StandardLockService] (default task-16) Successfully released change log lock
2020-10-13 02:04:55,944 WARNING [javax.enterprise.resource.webcontainer.jsf.flash] (default task-16) JSF1095: The response was already committed by the time we tried to set the outgoing cookie for the flash.  Any values stored to the flash will not be available on the next request.
2020-10-13 02:04:58,868 INFO  [org.meveo.service.custom.CustomTableCreatorService] (default task-16) Removing table audit_social_account
2020-10-13 02:04:58,878 INFO  [liquibase.executor.jvm.JdbcExecutor] (default task-16) SELECT COUNT(*) FROM public.databasechangeloglock
2020-10-13 02:04:58,878 INFO  [liquibase.executor.jvm.JdbcExecutor] (default task-16) SELECT COUNT(*) FROM public.databasechangeloglock
2020-10-13 02:04:58,879 INFO  [liquibase.executor.jvm.JdbcExecutor] (default task-16) SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1
2020-10-13 02:04:58,882 INFO  [liquibase.lockservice.StandardLockService] (default task-16) Successfully acquired change log lock
2020-10-13 02:04:58,904 INFO  [liquibase.executor.jvm.JdbcExecutor] (default task-16) SELECT MD5SUM FROM public.databasechangelog WHERE MD5SUM IS NOT NULL LIMIT 1
2020-10-13 02:04:58,905 INFO  [liquibase.executor.jvm.JdbcExecutor] (default task-16) SELECT COUNT(*) FROM public.databasechangelog
2020-10-13 02:04:58,906 INFO  [liquibase.changelog.StandardChangeLogHistoryService] (default task-16) Reading from public.databasechangelog
2020-10-13 02:04:58,906 INFO  [liquibase.executor.jvm.JdbcExecutor] (default task-16) SELECT * FROM public.databasechangelog ORDER BY DATEEXECUTED ASC, ORDEREXECUTED ASC
2020-10-13 02:04:58,922 INFO  [liquibase.executor.jvm.JdbcExecutor] (default task-16) DROP TABLE public.audit_social_account CASCADE
2020-10-13 02:04:58,924 INFO  [liquibase.changelog.ChangeSet] (default task-16) Table audit_social_account dropped
2020-10-13 02:04:58,926 INFO  [liquibase.changelog.ChangeSet] (default task-16) ChangeSet meveo::audit_social_account_CT_R_1602547498868::Meveo ran successfully in 7ms
2020-10-13 02:04:58,926 INFO  [liquibase.executor.jvm.JdbcExecutor] (default task-16) SELECT MAX(ORDEREXECUTED) FROM public.databasechangelog
2020-10-13 02:04:58,927 INFO  [liquibase.executor.jvm.JdbcExecutor] (default task-16) INSERT INTO public.databasechangelog (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('audit_social_account_CT_R_1602547498868', 'Meveo', 'meveo', NOW(), 447, '8:19b4ec30176cbb6060b6e6830242a693', 'dropTable tableName=audit_social_account', '', 'EXECUTED', NULL, NULL, '3.8.5', '2547498912')
2020-10-13 02:04:58,931 INFO  [liquibase.executor.jvm.JdbcExecutor] (default task-16) DROP SEQUENCE public.audit_social_account_seq CASCADE
2020-10-13 02:04:58,933 INFO  [liquibase.changelog.ChangeSet] (default task-16) Change set meveo::audit_social_account_CT_CRP_1602547498870::Meveo failed, but failOnError was false.  Error: ERROR: sequence "audit_social_account_seq" does not exist [Failed SQL: (0) DROP SEQUENCE public.audit_social_account_seq CASCADE]
2020-10-13 02:04:58,936 INFO  [liquibase.lockservice.StandardLockService] (default task-16) Successfully released change log lock
2020-10-13 02:04:58,966 INFO  [org.meveo.service.custom.CustomEntityTemplateCompiler] (default task-16) Generating source file for CustomEntityTemplate[id=1, code=SOCIAL_ACCOUNT]
2020-10-13 02:05:00,000 INFO  [org.meveo.api.observers.OntologyObserver] (EJB default - 1) Ontology has changed, updating IDL definitions
2020-10-13 02:05:02,034 INFO  [org.meveo.jpa.CurrentRepositoryProvider] (default task-15) Setting current repository to default
2020-10-13 02:05:04,448 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (default task-13) SQL Error: 0, SQLState: 42P01
2020-10-13 02:05:04,449 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (default task-13) ERROR: relation "audit_social_account" does not exist
  Position: 22
2020-10-13 02:05:04,451 ERROR [org.jboss.as.ejb3.invocation] (default task-13) WFLYEJB0034: EJB Invocation failed on component CustomTableService for method public long org.meveo.service.base.NativePersistenceService.count(java.lang.String,java.lang.String,org.meveo.admin.util.pagination.PaginationConfiguration): javax.ejb.EJBException: javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
	at org.jboss.as.ejb3@18.0.1.Final//org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:246)
	at org.jboss.as.ejb3@18.0.1.Final//org.jboss.as.ejb3.tx.CMTTxInterceptor.required(CMTTxInterceptor.java:362)
	at org.jboss.as.ejb3@18.0.1.Final//org.jboss.as.ejb3.tx.CMTTxInterceptor.processInvocation(CMTTxInterceptor.java:144)
	at org.jboss.invocation@1.5.2.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.invocation@1.5.2.Final//org.jboss.invocation.InterceptorContext$Invocation.proceed(InterceptorContext.java:509)
	at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:72)
	at org.jboss.as.weld.common@18.0.1.Final//org.jboss.as.weld.ejb.EjbRequestScopeActivationInterceptor.processInvocation(EjbRequestScopeActivationInterceptor.java:89)
	at org.jboss.invocation@1.5.2.Final//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422) 
```

**Comment by smichea** [comment]
there is an easier way to reproduce :

Create a CET with a single String CFT
create a CEI
update the CET and set it auditable
update the CEI -> its ok
update the CET and set the CFT auditable
update the CEI-> ko

for some reason the audit table has been dropped

```
2020-10-13 02:17:39,919 INFO  [org.meveo.service.custom.CustomTableCreatorService] (default task-13) Removing table audit_test
2020-10-13 02:17:39,925 INFO  [liquibase.executor.jvm.JdbcExecutor] (default task-13) SELECT COUNT(*) FROM public.databasechangeloglock
2020-10-13 02:17:39,926 INFO  [liquibase.executor.jvm.JdbcExecutor] (default task-13) SELECT COUNT(*) FROM public.databasechangeloglock
2020-10-13 02:17:39,926 INFO  [liquibase.executor.jvm.JdbcExecutor] (default task-13) SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1
2020-10-13 02:17:39,929 INFO  [liquibase.lockservice.StandardLockService] (default task-13) Successfully acquired change log lock
2020-10-13 02:17:39,947 INFO  [liquibase.executor.jvm.JdbcExecutor] (default task-13) SELECT MD5SUM FROM public.databasechangelog WHERE MD5SUM IS NOT NULL LIMIT 1
2020-10-13 02:17:39,948 INFO  [liquibase.executor.jvm.JdbcExecutor] (default task-13) SELECT COUNT(*) FROM public.databasechangelog
2020-10-13 02:17:39,949 INFO  [liquibase.changelog.StandardChangeLogHistoryService] (default task-13) Reading from public.databasechangelog
2020-10-13 02:17:39,949 INFO  [liquibase.executor.jvm.JdbcExecutor] (default task-13) SELECT * FROM public.databasechangelog ORDER BY DATEEXECUTED ASC, ORDEREXECUTED ASC
2020-10-13 02:17:39,960 INFO  [liquibase.executor.jvm.JdbcExecutor] (default task-13) DROP TABLE public.audit_test CASCADE
2020-10-13 02:17:39,961 INFO  [liquibase.changelog.ChangeSet] (default task-13) Table audit_test dropped
2020-10-13 02:17:39,963 INFO  [liquibase.changelog.ChangeSet] (default task-13) ChangeSet meveo::audit_test_CT_R_1602548259919::Meveo ran successfully in 6ms
2020-10-13 02:17:39,964 INFO  [liquibase.executor.jvm.JdbcExecutor] (default task-13) SELECT MAX(ORDEREXECUTED) FROM public.databasechangelog
2020-10-13 02:17:39,964 INFO  [liquibase.executor.jvm.JdbcExecutor] (default task-13) INSERT INTO public.databasechangelog (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('audit_test_CT_R_1602548259919', 'Meveo', 'meveo', NOW(), 461, '8:d9ab756a46d7b4bc7ec1f4abcb7b9223', 'dropTable tableName=audit_test', '', 'EXECUTED', NULL, NULL, '3.8.5', '2548259954')
2020-10-13 02:17:39,968 INFO  [liquibase.executor.jvm.JdbcExecutor] (default task-13) DROP SEQUENCE public.audit_test_seq CASCADE
2020-10-13 02:17:39,969 INFO  [liquibase.changelog.ChangeSet] (default task-13) Change set meveo::audit_test_CT_CRP_1602548259919::Meveo failed, but failOnError was false.  Error: ERROR: sequence "audit_test_seq" does not exist [Failed SQL: (0) DROP SEQUENCE public.audit_test_seq CASCADE]
2020-10-13 02:17:39,972 INFO  [liquibase.lockservice.StandardLockService] (default task-13) Successfully released change log lock
```

**Comment by czetsuya** [comment]
@smichea Problem is not occurring in the latest version of master. Tested on clear database.
