### ISSUE TITLE
Prevent uninstall / remove of a module if another installed module is dependent of it

### ISSUE THREAD

**Issue by ClementBareth** [meveo-org/meveo#219]

**Comment by czetsuya** [comment]
Adding a module dependency is currently throwing:

`Caused by: javax.persistence.PersistenceException: org.hibernate.PersistentObjectException: detached entity passed to persist: org.meveo.model.module.MeveoModuleDependency
	at org.hibernate@5.3.13.Final//org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
	at org.hibernate@5.3.13.Final//org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1515)
	at org.hibernate@5.3.13.Final//org.hibernate.query.Query.getResultList(Query.java:132)
	at deployment.meveo.war//org.meveo.service.notification.GenericNotificationService.getApplicableNotificationsNoCache(GenericNotificationService.java:135)
	at deployment.meveo.war//org.meveo.service.notification.GenericNotificationService.getApplicableNotifications(GenericNotificationService.java:72)
`

**Comment by czetsuya** [comment]
To test:
1. Create a module ParentModule.
2. Create a second module, RandomModule.
3. Create a module ChildModule, and add ParentModule as a module dependency.
4. Delete the RandomModule. It should succeed.
5. Delete the ParentModule. An error should be thrown "Unable to delete a referenced module.".
*This works for uninstall as well.
