### ISSUE TITLE
git clone failure (Repository.getIdentifier)

### ISSUE THREAD

**Issue by sophieperrineau** [meveo-org/meveo#283]
I tried to clone the git repository from meveo to my local.
My git client managed to connect to meveo and list branches. But when i perform the clone it fails.
For the client, i tried eclipse and git-bash

the server logs contains this message : 
```
2020-12-16 11:02:43,995 ERROR [io.undertow.request] (default task-32) UT005023: Exception handling request to /xxxx/git/Meveo/git-upload-pack: java.lang.NoSuchMethodError: 'java.lang.String org.eclipse.jgit.lib.Repository.g
etIdentifier()'
        at deployment.xxxx.war//org.eclipse.jgit.http.server.ServletUtils.identify(ServletUtils.java:278)
        at deployment.xxxx.war//org.eclipse.jgit.http.server.UploadPackServlet.log(UploadPackServlet.java:237)
        at deployment.xxxx.war//org.eclipse.jgit.http.server.UploadPackServlet.doPost(UploadPackServlet.java:225)
        at javax.servlet.api@2.0.0.Final//javax.servlet.http.HttpServlet.service(HttpServlet.java:523)
        at javax.servlet.api@2.0.0.Final//javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
        at deployment.xxxx.war//org.eclipse.jgit.http.server.glue.UrlPipeline$Chain.doFilter(UrlPipeline.java:244)
        at deployment.xxxx.war//org.eclipse.jgit.http.server.UploadPackServlet$Factory.doFilter(UploadPackServlet.java:167)
        at deployment.xxxx.war//org.eclipse.jgit.http.server.glue.UrlPipeline$Chain.doFilter(UrlPipeline.java:242)
        at deployment.xxxx.war//org.eclipse.jgit.http.server.RepositoryFilter.doFilter(RepositoryFilter.java:145)
        at deployment.xxxx.war//org.eclipse.jgit.http.server.glue.UrlPipeline$Chain.doFilter(UrlPipeline.java:242)
        at deployment.xxxx.war//org.eclipse.jgit.http.server.NoCacheFilter.doFilter(NoCacheFilter.java:86)
        at deployment.xxxx.war//org.eclipse.jgit.http.server.glue.UrlPipeline$Chain.doFilter(UrlPipeline.java:242)
        at deployment.xxxx.war//org.eclipse.jgit.http.server.glue.UrlPipeline.service(UrlPipeline.java:221)
        at deployment.xxxx.war//org.eclipse.jgit.http.server.glue.SuffixPipeline.service(SuffixPipeline.java:103)
        at deployment.xxxx.war//org.eclipse.jgit.http.server.glue.MetaFilter.doFilter(MetaFilter.java:183)
        at deployment.xxxx.war//org.eclipse.jgit.http.server.glue.MetaServlet.service(MetaServlet.java:142)
        at deployment.xxxx.war//org.meveo.api.git.MeveoGitServlet.service(MeveoGitServlet.java:207)
```

**Comment by czetsuya** [comment]
@sophieperrineau I'm on Windows and I tried cloning using git bash without any problem.

![image](https://user-images.githubusercontent.com/804528/102750429-b971bf80-43a0-11eb-9342-91e9d54eb85c.png)

**Comment by ClementBareth** [comment]
I think the problem here is that the Meveo repository was not correctly initialized, in most of the cases, a restart is enough. I already had the case where that repository was not initialized correctly. I will check further

**Comment by czetsuya** [comment]
Tested locally without issue:

![image](https://user-images.githubusercontent.com/804528/103605862-fb2d6900-4f4f-11eb-8699-edf652fa1da5.png)

**Comment by sophieperrineau** [comment]
problem fixed
