### ISSUE TITLE
Error displaying CEI detail when a custom action has an EL parsing error

### ISSUE THREAD

**Issue by smichea** [meveo-org/meveo#349]
When a CET has a custom action whose conditional EL has a parsing error like ` #{entity.fiel neq null} `  ( `neq` is invalid) then we cannot display the detail page of a CEI

```
Caused by: javax.el.ELException: Problems calling function 'exp:evaluateToBooleanOneVariable'
	at org.glassfish.jakarta.el@3.0.2//com.sun.el.parser.AstFunction.getValue(AstFunction.java:188)
	at org.glassfish.jakarta.el@3.0.2//com.sun.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:202)
	at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.module.web.el.WeldValueExpression.getValue(WeldValueExpression.java:50)
	at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.module.web.el.WeldValueExpression.getValue(WeldValueExpression.java:50)
	at com.sun.jsf-impl@2.3.9.SP04//com.sun.faces.facelets.el.ContextualCompositeValueExpression.getValue(ContextualCompositeValueExpression.java:117)
	at com.sun.jsf-impl@2.3.9.SP04//com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:73)
	... 107 more
Caused by: org.meveo.elresolver.ELException: Error while evaluating expression #{entity.deployedApp neq null} : Error Parsing: #{entity.deployedApp neq null}
	at deployment.meveo.war//org.meveo.elresolver.ValueExpressionWrapper.evaluateExpression(ValueExpressionWrapper.java:207)
	at deployment.meveo.war//org.meveo.elresolver.ValueExpressionWrapper.evaluateToBooleanMultiVariable(ValueExpressionWrapper.java:117)
	at deployment.meveo.war//org.meveo.service.base.MeveoValueExpressionWrapper.evaluateToBooleanOneVariable(MeveoValueExpressionWrapper.java:45)
	at jdk.internal.reflect.GeneratedMethodAccessor546.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.glassfish.jakarta.el@3.0.2//com.sun.el.parser.AstFunction.getValue(AstFunction.java:182)
	... 112 more
```

**Comment by czetsuya** [comment]
@smichea 

The conditionEL must be updated to: #{entity.cfValues.hasCfValue("field") ne null}

Note:
- Use ne instead of neq
- To check if a CET field is set in a CEI use entity.cfValues.hasCfValue("fieldName")

**Comment by czetsuya** [comment]
TODO: Catch the exception.

**Comment by smichea** [comment]
![image](https://user-images.githubusercontent.com/16659140/120443164-a8cd6880-c386-11eb-9849-b33699ed2f66.png)


all good
