### ISSUE TITLE
cannot use CEI with referenced entity in CrudScript

### ISSUE THREAD

**Issue by smichea** [meveo-org/meveo#356]
when adding a crudscrip to a CET that have a CFT of type "reference to entity", we get when trying to persist :
```
2021-05-27 09:45:32,492 ERROR [org.meveo.admin.action.admin.custom.CustomEntityInstanceBean] (default task-6) Cannot create or update CEI: java.lang.ClassCastException: class org.meveo.model.crm.EntityReferenceWrapper cannot be cast to class java.lang.String (org.meveo.model.crm.EntityReferenceWrapper is in unnamed module of loader 'deployment.meveo.war' @45f980ec; java.lang.String is in module java.base of loader 'bootstrap')
	at deployment.meveo.war//org.meveo.model.persistence.CEIUtils.deserialize(CEIUtils.java:590)
	at deployment.meveo.war//org.meveo.model.persistence.CEIUtils.ceiToPojo(CEIUtils.java:524)
	at deployment.meveo.war//org.meveo.persistence.CrossStorageService.createOrUpdate(CrossStorageService.java:714)
```

**Comment by smichea** [comment]
tried with 

```
package com.webdrone.proxy;

import org.meveo.service.script.Script;
import org.meveo.service.storage.RepositoryService;
import org.meveo.model.storage.Repository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import java.util.List;
import javax.management.RuntimeErrorException;
import org.meveo.api.persistence.CrossStorageApi;
import org.meveo.model.customEntities.proxyDomainCommand;
import org.meveo.model.customEntities.CrudEventListenerScript;
import org.meveo.api.persistence.CrossStorageRequest;
import org.meveo.model.customEntities.PROXY_DEPLOYMNT;
import org.meveo.model.customEntities.PROXY_GROUP;
import org.meveo.model.customEntities.PROXY_PROVIDER;
import org.meveo.model.customEntities.PROXY;


public class proxyDomainCommandCRUDScript extends Script implements CrudEventListenerScript<proxyDomainCommand> {

    private static final Logger log = LoggerFactory.getLogger(proxyDomainCommandCRUDScript.class);

    private CrossStorageApi crossStorageApi = getCDIBean(CrossStorageApi.class);

    private RepositoryService repositoryService = getCDIBean(RepositoryService.class);

    private Repository defaultRepo = repositoryService.findDefaultRepository();

    public Class<proxyDomainCommand> getEntityClass() {
        return proxyDomainCommand.class;
    }

    /**
     *  Called just before entity persistence
     *
     *  @param entity entity being persisted
     */
    public void prePersist(proxyDomainCommand entity) {
    }

    /**
     *  Called just before entity update
     *
     *  @param entity entity being updated
     */
    public void preUpdate(proxyDomainCommand entity) {
        throw new RuntimeException("no no no, you cannot update a command");
    }

    /**
     *  Called just before entity removal
     *
     *  @param entity entity being removed
     */
    public void preRemove(proxyDomainCommand entity) {
        throw new RuntimeException("no no no, you cannot delete a command");
    }

    public void postPersist(proxyDomainCommand entity) {
        // TODO
        PROXY_GROUP group = entity.getProxyGroup();
        String proxyGroupUuid = group.getUuid();
        // String appInstanceUuid = ((CustomEntityInstance)cftMap.get("deployedAppInstance")).getUuid();
        CrossStorageRequest<PROXY> csRequest = crossStorageApi.find(defaultRepo, PROXY.class);
        csRequest.by("group", proxyGroupUuid);
        List<PROXY> proxies = csRequest.getResults();
		log.info("postPersist , #proxies = {}",proxies.size());
        for (PROXY proxy : proxies) {
            try {
                CrossStorageRequest<PROXY_DEPLOYMNT> csRequest2 = crossStorageApi.find(defaultRepo, PROXY_DEPLOYMNT.class);
                csRequest2.by("proxy", proxy.getUuid());
                List<PROXY_DEPLOYMNT> proxyDeployments = csRequest2.getResults();
                int count2 = proxyDeployments.size();
				log.info("proxy {}, #proxyDeployments = {}",proxy.getUuid(),count2);
                if (count2 == 1) {
                    PROXY_DEPLOYMNT proxyDeployment = proxyDeployments.get(0);
                    if ("addExcludedDomain".equals(entity.getCommand())) {
                        List<String> pded = proxyDeployment.getExcludedDomains();
                        for (String domainToAdd : entity.getDomains()) {
                            if (!pded.contains(domainToAdd)) {
                                pded.add(domainToAdd);
								log.info("addExcludedDomain {}, to = {}",domainToAdd,proxyDeployment.getUuid());
                            }
                        }
                    } else if ("removeExcludedDomain".equals(entity.getCommand())) {
                        proxyDeployment.getExcludedDomains().removeAll(entity.getDomains());
                    }
                    try {
                        crossStorageApi.createOrUpdate(defaultRepo, proxyDeployment);
                    } catch (Exception e) {
                        e.printStackTrace();
                        log.error("cannot persist proxyDeployment");
                        throw new Exception("cannot persist proxyDeployment :" + e.getMessage());
                    }
                } else if (count2 == 0) {
                    log.info(" proxy :" + proxy.getUuid() + " is not deployed. ");
                } else {
                    log.info(" proxy :" + proxy.getUuid() + " is deployed more than once. ");
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }

    /**
     *  Called just after entity update
     *
     *  @param entity updated entity
     */
    public void postUpdate(proxyDomainCommand entity) {
    }

    /**
     *  Called just after entity removal
     *
     *  @param entity removed entity
     */
    public void postRemove(proxyDomainCommand entity) {
    }
}
```
