### ISSUE TITLE
error when adding CEI to module

### ISSUE THREAD

**Issue by smichea** [meveo-org/meveo#358]
in meveo admin module detail screen, when trying to add en entity to the module and selecting "Custom Entity Instance" the list is still blank and we have the following error in the logs :

```
2021-06-02 07:29:31,566 ERROR [org.jboss.as.ejb3.invocation] (default task-1) WFLYEJB0034: EJB Invocation failed on component CustomFieldInstanceService for method public void org.meveo.service.crm.impl.CustomFieldInstanceService.setCfValues(org.meveo.model.ICustomFieldEntity,java.lang.String,java.util.Map) throws org.meveo.admin.exception.BusinessException: java.lang.IllegalStateException: WFLYEJB0060: Wrong tx on thread: expected Local transaction (delegate=TransactionImple < ac, BasicAction: 0:ffffac120004:5657ea40:60b732bb:910 status: ActionStatus.COMMITTED >, owner=Local transaction context for provider JBoss JTA transaction provider), actual null
	at org.jboss.as.ejb3@18.0.1.Final//org.jboss.as.ejb3.tx.CMTTxInterceptor.endTransaction(CMTTxInterceptor.java:80)
	
...
2021-06-02 07:29:31,567 SEVERE [javax.enterprise.resource.webcontainer.jsf.application] (default task-1) Error Rendering View[/pages/admin/module/moduleDetail.xhtml]: javax.el.ELException: /taglib/genericEntityPopup.xhtml @121,181 value="#{genericEntityPickerBean.customEntityInstances}": java.lang.IllegalStateException: WFLYEJB0060: Wrong tx on thread: expected Local transaction (delegate=TransactionImple < ac, BasicAction: 0:ffffac120004:5657ea40:60b732bb:910 status: ActionStatus.COMMITTED >, owner=Local transaction context for provider JBoss JTA transaction provider), actual null
	at com.sun.jsf-impl@2.3.9.SP04//com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:77)
```

**Comment by czetsuya** [comment]
I'm able to add a CEI in a module:
![image](https://user-images.githubusercontent.com/804528/123961496-01723e80-d9e3-11eb-92a4-149a8a127a4b.png)
