### ISSUE TITLE
cannot create intial git repository

### ISSUE THREAD

**Issue by smichea** [meveo-org/meveo#477]
when starting meveo from docker with empty volumes we get the exception
```
02:35:32,223 DEBUG [org.meveo.persistence.sql.SqlConfigurationService] (ServerService Thread Pool -- 114) Start creation of entity SqlConfiguration
02:35:32,248 DEBUG [org.meveo.service.storage.RepositoryService] (ServerService Thread Pool -- 114) Start creation of entity Repository
02:35:32,251 INFO  [org.meveo.admin.listener.StartupListener] (ServerService Thread Pool -- 114) Created default repository
02:35:32,539 DEBUG [org.meveo.service.git.GitRepositoryService] (ServerService Thread Pool -- 114) Start creation of entity GitRepository
02:35:32,539 DEBUG [org.meveo.service.notification.DefaultObserver] (ServerService Thread Pool -- 114) Defaut observer : Entity org.meveo.model.git.GitRepository with id null created
02:35:32,556 INFO  [org.meveo.admin.listener.StartupListener] (ServerService Thread Pool -- 114) Created Meveo GIT repository
02:35:32,627 DEBUG [org.meveo.service.admin.impl.MeveoModuleService] (ServerService Thread Pool -- 114) No MeveoModule of code Meveo found
02:35:32,637 ERROR [org.jboss.as.ejb3.invocation] (ServerService Thread Pool -- 114) WFLYEJB0034: EJB Invocation failed on component MavenConfigurationService for method public void org.meveo.service.config.impl.MavenConfigurationService.createDefaultPomFile(java.lang.String): javax.ejb.EJBTransactionRolledbackException

Caused by: java.lang.NullPointerException
        at deployment.meveo.war//org.meveo.service.config.impl.MavenConfigurationService.generatePom(MavenConfigurationService.java:289)
        at deployment.meveo.war//org.meveo.service.config.impl.MavenConfigurationService.createDefaultPomFile(MavenConfigurationService.java:646)
```

**Comment by smichea** [comment]
solved by reinstalling wsl2
