### ISSUE TITLE
Scripts inheritance : Validation error on module install

### ISSUE THREAD

**Issue by QuentinTixier** [meveo-org/meveo#540]

**Comment by ClementBareth** [comment]
use case : 

- module A contains the CET Cet1
- module B contains a script S1 that extends another script S2 that uses Cet1. 

Problem 1 : When importing module B, S2 should be installed before S1 : 
`Caused by: java.lang.RuntimeException: No declaration found for extended type EndpointScript
	at deployment.meveo.war//org.meveo.service.script.CustomScriptService.lambda$25(CustomScriptService.java:805)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at deployment.meveo.war//org.meveo.service.script.CustomScriptService.beforeUpdateOrCreate(CustomScriptService.java:805)
	at deployment.meveo.war//org.meveo.service.script.ScriptInstanceService.beforeUpdateOrCreate(ScriptInstanceService.java:98)
	at deployment.meveo.war//org.meveo.service.script.ScriptInstanceService.beforeUpdateOrCreate(ScriptInstanceService.java:1)
	at deployment.meveo.war//org.meveo.service.script.CustomScriptService.beforeUpdateOrCreate(CustomScriptService.java:1)
	at deployment.meveo.war//org.meveo.service.script.FunctionService.create(FunctionService.java:164)`



Problem 2 : During script db insertion, we scan getter / setter of the script as well as the getter / setter of the super type. Problem is that the CET .class file are generated during script compilation, which occurs at the end of the installation

**Comment by sophieperrineau** [comment]
Curently, as a workaround we created a 3rd moule which contains the super script and is installed before ModuleB.
Module installation is OK, but modification of the scripts of moduleB with meveo-ui fails : Most of times, we need to save again the super script, just before saving a chid script
