### ISSUE TITLE
Delete endpoints encounter NPE on EndpointServlet

### ISSUE THREAD

**Issue by tonysviews** [meveo-org/meveo#555]
**Describe the bug**
When a DELETE endpoint is invoked, a NullPointerException is thrown from the EndpointServlet

**To Reproduce**
1. Create a new Delete endpoint.
2. Invoke the endpoint
3. A NulPointerException is thrown

**Expected behavior**
The endpoint should be invoked without errors.

**Comment by tonysviews** [comment]
error log:

ERROR [org.meveo.api.rest.technicalservice.EndpointServlet] (default task-2) Error while executing request: java.lang.NullPointerException
        at deployment.meveo.war//org.meveo.api.rest.technicalservice.EndpointServlet.doRequest(EndpointServlet.java:251)
        at deployment.meveo.war//org.meveo.api.rest.technicalservice.EndpointServlet.doDelete(EndpointServlet.java:106)

**Comment by tonysviews** [comment]
fixed in https://github.com/meveo-org/meveo/commit/f6063d5fcefd9a5fadc8965a30cee7b1a466e1ab
