### ISSUE TITLE
Cannot set endpoint to secured

### ISSUE THREAD

**Issue by tonysviews** [meveo-org/meveo#567]
**Describe the bug**
When an endpoint is not secured and we try to change it to be secured, an error is thrown

**To Reproduce**
1. Create an endpoint that is not secured.
2. Save the new endpoint
3. Open the endpoint again
4. Set it to secured then try to save
5. A EL Exception is thrown

**Expected behavior**
The endpoint should be set to secured without errors

**Screenshots**
![image](https://user-images.githubusercontent.com/6660853/174258041-b1990249-1820-4678-b519-797ec99f8334.png)

**Additional context**
Error log
```
08:17:52,974 ERROR [io.undertow.request] (default task-31) UT005023: Exception handling request to /meveo/pages/admin/endpoint/technicalServiceEndpointDetail.jsf: javax.servlet.ServletException: /taglib/formTextField.xhtml @21,145 value="#{fieldItem}": /taglib/formField.xhtml @274,159 fieldItem="#{fieldItem}": /taglib/formField.xhtml @184,71 value="${entity[field][childField]}": Target Unreachable, 'null' returned null
        at javax.faces.api@3.0.0.Final//javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:725)
        at javax.faces.api@3.0.0.Final//javax.faces.webapp.FacesServlet.service(FacesServlet.java:451)
        at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
        at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
        at io.undertow.websocket@2.0.27.Final//io.undertow.websockets.jsr.JsrWebSocketFilter.doFilter(JsrWebSocketFilter.java:173)
        at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at io.opentracing.contrib.opentracing-jaxrs2//io.opentracing.contrib.jaxrs2.server.SpanFinishingFilter.doFilter(SpanFinishingFilter.java:52)
        at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at deployment.meveo.war//org.meveo.admin.web.filter.RedirectToStaleSessionFilter.doFilter(RedirectToStaleSessionFilter.java:57)
        at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at deployment.meveo.war//org.meveo.admin.web.filter.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:27)
        at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
        at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
        at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
        at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
        at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
        at io.undertow.core@2.0.27.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at org.keycloak.keycloak-undertow-adapter@10.0.2//org.keycloak.adapters.undertow.UndertowAuthenticatedActionsHandler.handleRequest(UndertowAuthenticatedActionsHandler.java:66)
        at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
        at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
        at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
        at io.undertow.core@2.0.27.Final//io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33)
        at io.undertow.core@2.0.27.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.core@2.0.27.Final//io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)
        at io.undertow.core@2.0.27.Final//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
        at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
        at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)
        at io.undertow.core@2.0.27.Final//io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
        at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
        at io.undertow.core@2.0.27.Final//io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
        at io.undertow.core@2.0.27.Final//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
        at io.undertow.core@2.0.27.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
        at io.undertow.core@2.0.27.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.RewriteCorrectingHandlerWrappers$PostWrapper$1.handleRequest(RewriteCorrectingHandlerWrappers.java:71)
        at io.undertow.core@2.0.27.Final//io.undertow.predicate.PredicatesHandler.handleRequest(PredicatesHandler.java:110)
        at deployment.meveo.war//org.meveo.undertow.MaxPostSizeHandler.handleRequest(MaxPostSizeHandler.java:44)
        at io.undertow.core@2.0.27.Final//io.undertow.predicate.PredicatesHandler.handleRequest(PredicatesHandler.java:93)
        at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.RewriteCorrectingHandlerWrappers$PreWrapper$1.handleRequest(RewriteCorrectingHandlerWrappers.java:52)
        at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
        at org.keycloak.keycloak-undertow-adapter@10.0.2//org.keycloak.adapters.undertow.ServletPreAuthActionsHandler.handleRequest(ServletPreAuthActionsHandler.java:69)
        at io.undertow.core@2.0.27.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269)
        at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78)
        at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133)
        at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130)
        at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
        at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
        at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
        at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
        at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
        at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
        at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
        at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249)
        at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78)
        at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99)
        at io.undertow.core@2.0.27.Final//io.undertow.server.Connectors.executeRootHandler(Connectors.java:376)
        at io.undertow.core@2.0.27.Final//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
        at org.jboss.threads@2.3.3.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
        at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
        at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: javax.el.PropertyNotFoundException: /taglib/formTextField.xhtml @21,145 value="#{fieldItem}": /taglib/formField.xhtml @274,159 fieldItem="#{fieldItem}": /taglib/formField.xhtml @184,71 value="${entity[field][childField]}": Target Unreachable, 'null' returned null
        at com.sun.jsf-impl@2.3.9.SP04//com.sun.faces.facelets.el.TagValueExpression.getType(TagValueExpression.java:64)
        at deployment.meveo.war//org.primefaces.util.ComponentUtils.getConverter(ComponentUtils.java:164)
        at deployment.meveo.war//org.primefaces.renderkit.InputRenderer.getConvertedValue(InputRenderer.java:45)
        at javax.faces.api@3.0.0.Final//javax.faces.component.UIInput.getConvertedValue(UIInput.java:1105)
        at javax.faces.api@3.0.0.Final//javax.faces.component.UIInput.validate(UIInput.java:1006)
        at javax.faces.api@3.0.0.Final//javax.faces.component.UIInput.executeValidate(UIInput.java:1317)
        at javax.faces.api@3.0.0.Final//javax.faces.component.UIInput.processValidators(UIInput.java:733)
        at javax.faces.api@3.0.0.Final//javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:921)
        at javax.faces.api@3.0.0.Final//javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:921)
        at javax.faces.api@3.0.0.Final//javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:921)
        at deployment.meveo.war//org.primefaces.component.fieldset.Fieldset.processValidators(Fieldset.java:109)
        at javax.faces.api@3.0.0.Final//javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:921)
        at deployment.meveo.war//org.primefaces.component.outputpanel.OutputPanel.processValidators(OutputPanel.java:91)
        at javax.faces.api@3.0.0.Final//javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:921)
        at javax.faces.api@3.0.0.Final//javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:921)
        at deployment.meveo.war//org.primefaces.component.panel.Panel.processValidators(Panel.java:147)
        at javax.faces.api@3.0.0.Final//javax.faces.component.UIForm.processValidators(UIForm.java:229)
        at javax.faces.api@3.0.0.Final//javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:921)
        at javax.faces.api@3.0.0.Final//javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:921)
        at javax.faces.api@3.0.0.Final//javax.faces.component.UIViewRoot.processValidators(UIViewRoot.java:1309)
        at com.sun.jsf-impl@2.3.9.SP04//com.sun.faces.lifecycle.ProcessValidationsPhase.execute(ProcessValidationsPhase.java:53)
        at com.sun.jsf-impl@2.3.9.SP04//com.sun.faces.lifecycle.Phase.doPhase(Phase.java:76)
        at com.sun.jsf-impl@2.3.9.SP04//com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:177)
        at javax.faces.api@3.0.0.Final//javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:707)
        ... 68 more
Caused by: javax.el.PropertyNotFoundException: /taglib/formField.xhtml @274,159 fieldItem="#{fieldItem}": /taglib/formField.xhtml @184,71 value="${entity[field][childField]}": Target Unreachable, 'null' returned null
        at com.sun.jsf-impl@2.3.9.SP04//com.sun.faces.facelets.el.TagValueExpression.getType(TagValueExpression.java:64)
        at org.glassfish.jakarta.el@3.0.2//com.sun.el.parser.AstIdentifier.getType(AstIdentifier.java:55)
        at org.glassfish.jakarta.el@3.0.2//com.sun.el.ValueExpressionImpl.getType(ValueExpressionImpl.java:177)
        at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.module.web.el.WeldValueExpression.getType(WeldValueExpression.java:93)
        at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.module.web.el.WeldValueExpression.getType(WeldValueExpression.java:93)
        at com.sun.jsf-impl@2.3.9.SP04//com.sun.faces.facelets.el.TagValueExpression.getType(TagValueExpression.java:62)
        ... 91 more
Caused by: javax.el.PropertyNotFoundException: /taglib/formField.xhtml @184,71 value="${entity[field][childField]}": Target Unreachable, 'null' returned null
        at com.sun.jsf-impl@2.3.9.SP04//com.sun.faces.facelets.el.TagValueExpression.getType(TagValueExpression.java:64)
        at org.glassfish.jakarta.el@3.0.2//com.sun.el.parser.AstIdentifier.getType(AstIdentifier.java:55)
        at org.glassfish.jakarta.el@3.0.2//com.sun.el.ValueExpressionImpl.getType(ValueExpressionImpl.java:177)
        at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.module.web.el.WeldValueExpression.getType(WeldValueExpression.java:93)
        at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.module.web.el.WeldValueExpression.getType(WeldValueExpression.java:93)
        at com.sun.jsf-impl@2.3.9.SP04//com.sun.faces.facelets.el.TagValueExpression.getType(TagValueExpression.java:62)
        ... 96 more
Caused by: javax.el.PropertyNotFoundException: Target Unreachable, 'null' returned null
        at org.glassfish.jakarta.el@3.0.2//com.sun.el.parser.AstValue.getTarget(AstValue.java:167)
        at org.glassfish.jakarta.el@3.0.2//com.sun.el.parser.AstValue.getType(AstValue.java:61)
        at org.glassfish.jakarta.el@3.0.2//com.sun.el.ValueExpressionImpl.getType(ValueExpressionImpl.java:177)
        at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.module.web.el.WeldValueExpression.getType(WeldValueExpression.java:93)
        at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.module.web.el.WeldValueExpression.getType(WeldValueExpression.java:93)
        at com.sun.jsf-impl@2.3.9.SP04//com.sun.faces.facelets.el.TagValueExpression.getType(TagValueExpression.java:62)
        ... 101 more
```

**Comment by tonysviews** [comment]
Just to document the workaround:

If the endpoint is in a module that is in github, just modify the endpoint json in github and pull the repository in meveo to update the endpoint.

Otherwise, use the [endpoint API](https://github.com/meveo-org/meveo/tree/master/meveo-admin/ejbs/src/main/java/org/meveo/service/technicalservice/endpoint#how-to-use-an-endpoint) to update the endpoint.  The easiest way to do it, is to use the GET method to retrieve the endpoint details, then update the field and save using the PUT method.
