### ISSUE TITLE
concurrent access timeout on CustomFieldsCacheContainerProvider

### ISSUE THREAD

**Issue by sophieperrineau** [meveo-org/meveo#623]
Randomly, this error occurs when saving a custom entity 

`Caused by: javax.ejb.ConcurrentAccessTimeoutException: WFLYEJB0241: EJB 3.1 PFD2 4.8.5.5.1 concurrent access timeout on CustomFieldsCacheContainerProvider - could not obtain lock within 5000MILLISECONDS
        at org.jboss.as.ejb3@18.0.1.Final//org.jboss.as.ejb3.component.singleton.ContainerManagedConcurrencyInterceptor.processInvocation(ContainerManagedConcurrencyInterceptor.java:102)
 ..
        at deployment.meveo.war//org.meveo.cache.CustomFieldsCacheContainerProvider$$$view13.getCustomFieldTemplates(Unknown Source)
 ..
        at deployment.meveo.war//org.meveo.cache.CustomFieldsCacheContainerProvider$Proxy$_$$_Weld$EnterpriseProxy$.getCustomFieldTemplates(Unknown Source)
        at deployment.meveo.war//org.meveo.service.crm.impl.CustomFieldTemplateService.findByAppliesTo(CustomFieldTemplateService.java:199)
        at deployment.meveo.war//org.meveo.service.crm.impl.CustomFieldTemplateService.findByAppliesTo(CustomFieldTemplateService.java:155)
..
        at deployment.meveo.war//org.meveo.service.crm.impl.CustomFieldInstanceService.setCfValues(CustomFieldInstanceService.java:2423)
..
        at deployment.meveo.war//org.meveo.service.crm.impl.CustomFieldInstanceService$Proxy$_$$_Weld$EnterpriseProxy$.setCfValues(Unknown Source)
        at deployment.meveo.war//org.meveo.service.custom.CustomEntityInstanceService.fromMap(CustomEntityInstanceService.java:127)
..
        at deployment.meveo.war//org.meveo.service.custom.CustomEntityInstanceService$Proxy$_$$_Weld$EnterpriseProxy$.fromMap(Unknown Source)
        at deployment.meveo.war//org.meveo.persistence.CrossStorageService.createCetReference(CrossStorageService.java:945)
        at deployment.meveo.war//org.meveo.persistence.CrossStorageService.createEntityReferences(CrossStorageService.java:805)
        at deployment.meveo.war//org.meveo.persistence.CrossStorageService.createOrUpdate(CrossStorageService.java:462)
`

we'd like a fix on branch 7.1

**Comment by sophieperrineau** [comment]
`
ERROR [org.jboss.as.ejb3.invocation] (ForkJoinPool-31-worker-127) WFLYEJB0034: EJB Invocation failed on component CustomFieldInstanceService for method public void org.meveo.service.crm.impl.CustomFieldInstanceSer
vice.setCfValues(org.meveo.model.ICustomFieldEntity,java.lang.String,java.util.Map) throws org.meveo.admin.exception.BusinessException: javax.ejb.EJBTransactionRolledbackException: WFLYEJB0241: EJB 3.1 PFD2 4.8.5.5.1 concurrent access ti
meout on CustomFieldsCacheContainerProvider - could not obtain lock within 5000MILLISECONDS
        at deployment.meveo.war//org.meveo.service.crm.impl.CustomFieldTemplateService$$$view181.findByCodeAndAppliesTo(Unknown Source)

        at deployment.meveo.war//org.meveo.service.crm.impl.CustomFieldTemplateService$Proxy$_$$_Weld$EnterpriseProxy$.findByCodeAndAppliesTo(Unknown Source)
        at deployment.meveo.war//org.meveo.service.crm.impl.CustomFieldInstanceService.setCFValue(CustomFieldInstanceService.java:545)
        at deployment.meveo.war//org.meveo.service.crm.impl.CustomFieldInstanceService.setCfValues(CustomFieldInstanceService.java:2468)
....
        at deployment.meveo.war//org.meveo.service.crm.impl.CustomFieldInstanceService$Proxy$_$$_Weld$EnterpriseProxy$.setCfValues(Unknown Source)
        at deployment.meveo.war//org.meveo.persistence.CrossStorageService.createOrUpdate(CrossStorageService.java:463)
 `
