### ISSUE TITLE
Missing CFT

### ISSUE THREAD

**Issue by tonysviews** [meveo-org/meveo#706]
**Describe the bug**
A CFT will disappear from the admin GUI when it is removed, then added back with a different type.

**To Reproduce**
1. Create a new CFT as a specific type e.g. name: address  type:String
2. Save the new CFT and CET.
3. Delete the CFT.
4. Create a new CFT with the same name e.g. name:address type:Reference to Entity
5. The CFT will not be visible and the entity's list page can no longer be accessed. The CET also cannot be retrieved using persistence API.

> Note: The entity list page can be restored by going to the Module and delete the blank CFT under the CET, then restoring the CFT with the original type.

**Expected behavior**
Either an error is thrown when creating a new CFT with a deleted CFT's name with a different type
or
Delete the old CFT completely and allow the new CFT with a different type to be recreated without errors

**Screenshots**
Accessing the entity list page:
![image](https://user-images.githubusercontent.com/6660853/229003988-70a57a43-d277-4c06-a954-a35fa03ae9d9.png)

Retrieving via persistence API:
![image](https://user-images.githubusercontent.com/6660853/229003806-97de8f50-b462-4001-9140-6edaf0cac462.png)

The `address` CFT is missing in the Entity Customization page
![image](https://user-images.githubusercontent.com/6660853/229004158-f15e5d9d-e645-45d6-a702-8d4e3ab33584.png)

After applying the workaround to get the Entity list to appear, we can see that the CFT appears in the form:
![image](https://user-images.githubusercontent.com/6660853/229004329-2f1b3d2f-4ade-45b5-9278-b378d1f1237e.png)

**Additional context**
Logs when accessing the entity list page:
```log
2023-03-31 01:18:50,103 ERROR [io.undertow.request] (default task-2061) UT005023: Exception handling request to /meveo/pages/admin/customEntities/customEntities.jsf: javax.servlet.ServletException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
	at javax.faces.api@3.0.0.Final//javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:725)
	at javax.faces.api@3.0.0.Final//javax.faces.webapp.FacesServlet.service(FacesServlet.java:451)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at io.undertow.websocket@2.0.27.Final//io.undertow.websockets.jsr.JsrWebSocketFilter.doFilter(JsrWebSocketFilter.java:173)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.opentracing.contrib.opentracing-jaxrs2//io.opentracing.contrib.jaxrs2.server.SpanFinishingFilter.doFilter(SpanFinishingFilter.java:52)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at deployment.meveo.war//org.meveo.admin.web.filter.RedirectToStaleSessionFilter.doFilter(RedirectToStaleSessionFilter.java:57)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at deployment.meveo.war//org.meveo.admin.web.filter.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:27)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.core@2.0.27.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.keycloak.keycloak-undertow-adapter@10.0.2//org.keycloak.adapters.undertow.UndertowAuthenticatedActionsHandler.handleRequest(UndertowAuthenticatedActionsHandler.java:66)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.core@2.0.27.Final//io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33)
	at io.undertow.core@2.0.27.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.core@2.0.27.Final//io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)
	at io.undertow.core@2.0.27.Final//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)
	at io.undertow.core@2.0.27.Final//io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.core@2.0.27.Final//io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.core@2.0.27.Final//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.core@2.0.27.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.core@2.0.27.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.RewriteCorrectingHandlerWrappers$PostWrapper$1.handleRequest(RewriteCorrectingHandlerWrappers.java:71)
	at io.undertow.core@2.0.27.Final//io.undertow.predicate.PredicatesHandler.handleRequest(PredicatesHandler.java:110)
	at deployment.meveo.war//org.meveo.undertow.MaxPostSizeHandler.handleRequest(MaxPostSizeHandler.java:44)
	at io.undertow.core@2.0.27.Final//io.undertow.predicate.PredicatesHandler.handleRequest(PredicatesHandler.java:93)
	at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.RewriteCorrectingHandlerWrappers$PreWrapper$1.handleRequest(RewriteCorrectingHandlerWrappers.java:52)
	at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
	at org.keycloak.keycloak-undertow-adapter@10.0.2//org.keycloak.adapters.undertow.ServletPreAuthActionsHandler.handleRequest(ServletPreAuthActionsHandler.java:69)
	at io.undertow.core@2.0.27.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
	at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
	at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
	at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
	at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99)
	at io.undertow.core@2.0.27.Final//io.undertow.server.Connectors.executeRootHandler(Connectors.java:376)
	at io.undertow.core@2.0.27.Final//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
	at org.hibernate@5.3.13.Final//org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
	at org.hibernate@5.3.13.Final//org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1515)
	at org.hibernate@5.3.13.Final//org.hibernate.query.internal.AbstractProducedQuery.getSingleResult(AbstractProducedQuery.java:1554)
	at deployment.meveo.war//org.meveo.service.base.NativePersistenceService.count(NativePersistenceService.java:1525)
	at deployment.meveo.war//org.meveo.service.custom.CustomTableService$Proxy$_$$_WeldSubclass.count(Unknown Source)
	at deployment.meveo.war//org.meveo.persistence.impl.SQLStorageImpl.count(SQLStorageImpl.java:445)
	at deployment.meveo.war//org.meveo.persistence.CrossStorageService.count(CrossStorageService.java:406)
	at deployment.meveo.war//org.meveo.util.view.CrossStorageDataModel.load(CrossStorageDataModel.java:77)
	at deployment.meveo.war//org.primefaces.component.datatable.DataTable.loadLazyData(DataTable.java:573)
	at deployment.meveo.war//org.primefaces.component.datatable.DataTableRenderer.preRender(DataTableRenderer.java:145)
	at deployment.meveo.war//org.primefaces.component.datatable.DataTableRenderer.encodeEnd(DataTableRenderer.java:93)
	at javax.faces.api@3.0.0.Final//javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:595)
	at javax.faces.api@3.0.0.Final//javax.faces.component.UIComponent.encodeAll(UIComponent.java:1654)
	at javax.faces.api@3.0.0.Final//javax.faces.render.Renderer.encodeChildren(Renderer.java:152)
	at javax.faces.api@3.0.0.Final//javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:566)
	at deployment.meveo.war//org.primefaces.renderkit.CoreRenderer.renderChild(CoreRenderer.java:82)
	at deployment.meveo.war//org.primefaces.renderkit.CoreRenderer.renderChildren(CoreRenderer.java:69)
	at deployment.meveo.war//org.primefaces.component.panel.PanelRenderer.encodeContent(PanelRenderer.java:219)
	at deployment.meveo.war//org.primefaces.component.panel.PanelRenderer.encodeMarkup(PanelRenderer.java:133)
	at deployment.meveo.war//org.primefaces.component.panel.PanelRenderer.encodeEnd(PanelRenderer.java:67)
	at javax.faces.api@3.0.0.Final//javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:595)
	at deployment.meveo.war//org.primefaces.renderkit.CoreRenderer.renderChild(CoreRenderer.java:87)
	at deployment.meveo.war//org.primefaces.renderkit.CoreRenderer.renderChildren(CoreRenderer.java:69)
	at deployment.meveo.war//org.primefaces.component.outputpanel.OutputPanelRenderer.encodeMarkup(OutputPanelRenderer.java:74)
	at deployment.meveo.war//org.primefaces.component.outputpanel.OutputPanelRenderer.encodeEnd(OutputPanelRenderer.java:48)
	at javax.faces.api@3.0.0.Final//javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:595)
	at javax.faces.api@3.0.0.Final//javax.faces.component.UIComponent.encodeAll(UIComponent.java:1654)
	at javax.faces.api@3.0.0.Final//javax.faces.component.UIComponent.encodeAll(UIComponent.java:1650)
	at javax.faces.api@3.0.0.Final//javax.faces.component.UIComponent.encodeAll(UIComponent.java:1650)
	at com.sun.jsf-impl@2.3.9.SP04//com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:468)
	at com.sun.jsf-impl@2.3.9.SP04//com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:170)
	at javax.faces.api@3.0.0.Final//javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:132)
	at javax.faces.api@3.0.0.Final//javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:132)
	at javax.faces.api@3.0.0.Final//javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:132)
	at deployment.meveo.war//org.omnifaces.viewhandler.OmniViewHandler.renderView(OmniViewHandler.java:121)
	at javax.faces.api@3.0.0.Final//javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:132)
	at javax.faces.api@3.0.0.Final//javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:132)
	at com.sun.jsf-impl@2.3.9.SP04//com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:102)
	at com.sun.jsf-impl@2.3.9.SP04//com.sun.faces.lifecycle.Phase.doPhase(Phase.java:76)
	at com.sun.jsf-impl@2.3.9.SP04//com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:199)
	at javax.faces.api@3.0.0.Final//javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:708)
	... 68 more
Caused by: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
	at org.hibernate@5.3.13.Final//org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:106)
	at org.hibernate@5.3.13.Final//org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
	at org.hibernate@5.3.13.Final//org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
	at org.hibernate@5.3.13.Final//org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
	at org.hibernate@5.3.13.Final//org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:69)
	at org.hibernate@5.3.13.Final//org.hibernate.loader.Loader.getResultSet(Loader.java:2265)
	at org.hibernate@5.3.13.Final//org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2028)
	at org.hibernate@5.3.13.Final//org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1990)
	at org.hibernate@5.3.13.Final//org.hibernate.loader.Loader.doQuery(Loader.java:949)
	at org.hibernate@5.3.13.Final//org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:351)
	at org.hibernate@5.3.13.Final//org.hibernate.loader.Loader.doList(Loader.java:2787)
	at org.hibernate@5.3.13.Final//org.hibernate.loader.Loader.doList(Loader.java:2770)
	at org.hibernate@5.3.13.Final//org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2604)
	at org.hibernate@5.3.13.Final//org.hibernate.loader.Loader.list(Loader.java:2599)
	at org.hibernate@5.3.13.Final//org.hibernate.loader.custom.CustomLoader.list(CustomLoader.java:338)
	at org.hibernate@5.3.13.Final//org.hibernate.internal.SessionImpl.listCustomQuery(SessionImpl.java:2254)
	at org.hibernate@5.3.13.Final//org.hibernate.internal.AbstractSharedSessionContract.list(AbstractSharedSessionContract.java:1069)
	at org.hibernate@5.3.13.Final//org.hibernate.query.internal.NativeQueryImpl.doList(NativeQueryImpl.java:170)
	at org.hibernate@5.3.13.Final//org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1506)
	... 107 more
Caused by: org.postgresql.util.PSQLException: ERROR: relation "crosschaintransfer" does not exist
  Position: 22
	at org.postgresql@42.2.5//org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql@42.2.5//org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql@42.2.5//org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql@42.2.5//org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql@42.2.5//org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql@42.2.5//org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
	at org.postgresql@42.2.5//org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:106)
	at org.jboss.ironjacamar.jdbcadapters@1.4.17.Final//org.jboss.jca.adapters.jdbc.WrappedPreparedStatement.executeQuery(WrappedPreparedStatement.java:504)
	at org.hibernate@5.3.13.Final//org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:60)
	... 121 more
```

**Comment by smichea** [comment]
from resolving #672 and #660 i manage to test without issue this case.
Note that deleting the CFT do not delete its CEI so they still appear but there is no link to the reference entity.
