### ISSUE TITLE
Cannot save CEI contain field with custom field type enum "DATE"

### ISSUE THREAD

**Issue by phubach** [meveo-org/meveo#92]
**Describe the bug**
Inside the CEI page, when save button is press the CEI contain the field with custom field type enum "DATE" is not saved .

**To Reproduce**
1. Create CET store as table = false and contain a field with custom field type enum "DATE"
2. Create CEI for the CET
3. Save CEI
4. See error:
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Cannot format given Object as a Date (through reference chain: java.util.HashMap["startDate"]->java.util.ArrayList[0]->org.meveo.model.crm.custom.CustomFieldValue["date"])
	at com.fasterxml.jackson.core.jackson-databind@2.9.10.1//com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394)
	at com.fasterxml.jackson.core.jackson-databind@2.9.10.1//com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:353)
	at com.fasterxml.jackson.core.jackson-databind@2.9.10.1//com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:316)
	at com.fasterxml.jackson.core.jackson-databind@2.9.10.1//com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:727)
	at com.fasterxml.jackson.core.jackson-databind@2.9.10.1//com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at com.fasterxml.jackson.core.jackson-databind@2.9.10.1//com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
	at com.fasterxml.jackson.core.jackson-databind@2.9.10.1//com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
	at com.fasterxml.jackson.core.jackson-databind@2.9.10.1//com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
	at com.fasterxml.jackson.core.jackson-databind@2.9.10.1//com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeOptionalFields(MapSerializer.java:782)
	at com.fasterxml.jackson.core.jackson-databind@2.9.10.1//com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:639)
	at com.fasterxml.jackson.core.jackson-databind@2.9.10.1//com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:33)
	at com.fasterxml.jackson.core.jackson-databind@2.9.10.1//com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.core.jackson-databind@2.9.10.1//com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.core.jackson-databind@2.9.10.1//com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3906)
	at com.fasterxml.jackson.core.jackson-databind@2.9.10.1//com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3220)
	at deployment.meveo.war//org.meveo.model.persistence.JacksonUtil.toString(JacksonUtil.java:79)
	... 274 more
Caused by: java.lang.IllegalArgumentException: Cannot format given Object as a Date
	at java.base/java.text.DateFormat.format(DateFormat.java:338)
	at java.base/java.text.Format.format(Format.java:158)
	at deployment.meveo.war//org.meveo.commons.utils.CustomInstantSerializer.serialize(CustomInstantSerializer.java:17)
	at deployment.meveo.war//org.meveo.commons.utils.CustomInstantSerializer.serialize(CustomInstantSerializer.java:12)
	at com.fasterxml.jackson.core.jackson-databind@2.9.10.1//com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.core.jackson-databind@2.9.10.1//com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	... 286 more

**Expected behavior**
CEI contain a field with custom field type enum "DATE" should be saved 

**Screenshots**
![issue](https://user-images.githubusercontent.com/9191276/88618741-0d170000-d0c4-11ea-8cba-ff50f58e445f.JPG)

**Comment by phubach** [comment]
duplicated ticket https://github.com/meveo-org/meveo/issues/71
