### ISSUE TITLE
Cannot save CEI instance with CFT of type date

### ISSUE THREAD

**Issue by czetsuya** [meveo-org/meveo#96]
**Describe the bug**
When creating a new CEI record from a CET with CFT of type date the record is not save and it throws an error.

**To Reproduce**
1. Create a new CET
2. Add CFT of type Date, set the format to yyyy-MM-dd
3. Open the CEI page and enter a new record
4. Hit save
5. An error is thrown

**Expected behavior**
CEI should be created with the correct date value.

**Additional context**
`Caused by: java.lang.IllegalArgumentException: Cannot format given Object as a Date
	at java.base/java.text.DateFormat.format(DateFormat.java:338)
	at java.base/java.text.Format.format(Format.java:158)
	at deployment.meveo.war//org.meveo.commons.utils.CustomInstantSerializer.serialize(CustomInstantSerializer.java:17)
	at deployment.meveo.war//org.meveo.commons.utils.CustomInstantSerializer.serialize(CustomInstantSerializer.java:1)`

**Comment by phubach** [comment]
This issue is related with https://github.com/meveo-org/meveo/issues/71
So I committed to https://github.com/meveo-org/meveo/issues/71
